/**
 * Auto-generated third-party integration API (`/api/v1`).
 *
 * Every route here is derived from the active inverter profile's entity
 * catalog — the catalog, the per-entity read routes, and one validated write
 * route per writable entity are all generated by looping {@link profile.metrics}.
 * Adding a metric to a profile (or installing a new inverter package) extends
 * this API and its OpenAPI docs with zero route code.
 *
 * Auth: guarded by `API_KEYS` (see the guard below). This is the external
 * surface; the web app's own session-authed endpoints live in `index.ts`.
 */

import { env } from "@ReyeON/env/server";
import type { EntityConstraint } from "@ReyeON/inverter-core";
import {
  buildManifest,
  entityConstraint,
  metricByKey,
  writableMetrics,
} from "@ReyeON/inverter-core";
import { Elysia, t } from "elysia";
import { queryRawHistory, queryRollup } from "./history";
import { profile } from "./inverter";
import { log } from "./logging";
import { liveState } from "./state";

const logger = log("api");
const manifest = buildManifest(profile);
const metaByKey = new Map(manifest.metrics.map((m) => [m.key, m]));
const defByKey = metricByKey(profile);

/**
 * Runtime validation for a write, shared by the internal command endpoint and
 * the external API (and, later, the MQTT command bridge). Returns an error
 * message or `null` when the value is acceptable for the entity. Enforces the
 * same bounds/enum the generated TypeBox schemas advertise.
 */
export function validateWrite(key: string, value: number): string | null {
  const def = defByKey.get(key);
  if (!def) return `Unknown entity: ${key}`;
  const c = entityConstraint(def);
  if (!c.writable) return `Entity is not writable: ${key}`;
  if (c.valueType === "enum") {
    return c.enumValues?.includes(value)
      ? null
      : `Value must be one of: ${c.enumValues?.join(", ")}`;
  }
  if (c.min !== undefined && value < c.min) return `Value ${value} is below minimum ${c.min}`;
  if (c.max !== undefined && value > c.max) return `Value ${value} is above maximum ${c.max}`;
  return null;
}

/** TypeBox validator for a writable entity's value, from its constraint. */
function valueSchema(c: EntityConstraint) {
  if (c.valueType === "enum" && c.enumValues && c.enumValues.length > 0) {
    return t.Union(c.enumValues.map((v) => t.Literal(v)));
  }
  const bounds: { minimum?: number; maximum?: number } = {};
  if (c.min !== undefined) bounds.minimum = c.min;
  if (c.max !== undefined) bounds.maximum = c.max;
  return t.Number(bounds);
}

/**
 * Reject requests without a valid API key. Empty `API_KEYS` is open in
 * development (local convenience) but fails closed in production so the public
 * surface is never accidentally unauthenticated.
 */
function checkApiKey(request: Request): { status: number; error: string } | null {
  const keys = env.API_KEYS;
  if (keys.length === 0) {
    if (env.NODE_ENV === "production") {
      return { status: 401, error: "API access is not configured" };
    }
    return null;
  }
  const header = request.headers.get("authorization");
  const bearer = header?.toLowerCase().startsWith("bearer ") ? header.slice(7).trim() : undefined;
  const provided = bearer ?? request.headers.get("x-api-key") ?? undefined;
  if (!provided || !keys.includes(provided)) {
    return { status: 401, error: "Invalid or missing API key" };
  }
  return null;
}

/** Injected transport dependencies (keeps this module free of the singleton). */
export interface EntitiesApiDeps {
  write(key: string, value: number): Promise<void>;
}

/** Mount the generated `/api/v1` integration API onto an Elysia app. */
export function entitiesApi(deps: EntitiesApiDeps) {
  const app = new Elysia({ prefix: "/api/v1", name: "entities" })
    .onError(({ error, code, set }) => {
      // Preserve the status of known request errors; sanitize everything else to
      // a generic 500 so internal stack traces never leak to third parties.
      if (code === "VALIDATION") {
        set.status = 422;
        return { error: "Validation failed", detail: error.message };
      }
      if (code === "PARSE") {
        set.status = 400;
        return { error: "Malformed request body" };
      }
      logger.error("{code}: {error}", {
        code,
        error: error instanceof Error ? error.stack : error,
      });
      set.status = 500;
      return { error: "Internal server error" };
    })
    .onBeforeHandle(({ request, set }) => {
      const denied = checkApiKey(request);
      if (denied) {
        set.status = denied.status;
        return { error: denied.error };
      }
    })
    // Entity catalog: identity, label, unit, kind, role, topic, writability,
    // bounds/enum. The discovery endpoint a consumer reads first.
    .get(
      "/entities",
      () => ({
        id: manifest.id,
        name: manifest.name,
        manufacturer: manifest.manufacturer,
        capabilities: manifest.capabilities,
        entities: manifest.metrics,
      }),
      {
        detail: {
          tags: ["Entities"],
          summary: "List entities",
          description: "Full catalog of entities the active inverter exposes.",
        },
      },
    )
    // Current value of every entity in one snapshot (from the live poll cache).
    .get(
      "/state",
      ({ set }) => {
        const sample = liveState.latest;
        if (!sample) {
          set.status = 503;
          return { error: "No sample available yet" };
        }
        return { time: sample.time, inverterId: sample.inverterId, values: sample.metrics };
      },
      {
        detail: {
          tags: ["Entities"],
          summary: "Current state",
          description: "Latest value of every entity from the most recent poll.",
        },
      },
    )
    // One entity's metadata plus its latest value.
    .get(
      "/entities/:key",
      ({ params, set }) => {
        const meta = metaByKey.get(params.key);
        if (!meta) {
          set.status = 404;
          return { error: `Unknown entity: ${params.key}` };
        }
        return { ...meta, value: liveState.latest?.metrics[params.key] ?? null };
      },
      {
        params: t.Object({ key: t.String() }),
        detail: {
          tags: ["Entities"],
          summary: "Get entity",
          description: "Metadata and latest value for a single entity.",
        },
      },
    )
    // Time series for one entity. Raw samples by default; pass `bucket` to read
    // the pre-aggregated TimescaleDB rollups (cheap over long windows).
    .get(
      "/entities/:key/history",
      async ({ params, query, set }) => {
        if (!metaByKey.has(params.key)) {
          set.status = 404;
          return { error: `Unknown entity: ${params.key}` };
        }
        const inverterId = query.inverterId ?? profile.id;
        const since = new Date(Date.now() - query.hours * 60 * 60 * 1000);
        const base = { metric: params.key, inverterId, since, limit: query.limit };
        return query.bucket
          ? queryRollup({ ...base, bucket: query.bucket })
          : queryRawHistory(base);
      },
      {
        params: t.Object({ key: t.String() }),
        query: t.Object({
          hours: t.Number({ default: 24, minimum: 1 }),
          limit: t.Number({ default: 5000, minimum: 1, maximum: 50000 }),
          bucket: t.Optional(t.Union([t.Literal("minute"), t.Literal("hour"), t.Literal("day")])),
          inverterId: t.Optional(t.String()),
        }),
        detail: {
          tags: ["Entities"],
          summary: "Entity history",
          description:
            "Time series for one entity: raw samples, or aggregated rollups when `bucket` is set.",
        },
      },
    );

  // One validated write route per writable entity. Bounds/enum come from the
  // entity's metadata, so each route documents (and enforces) exactly what it
  // accepts. We fold routes into the chain (capturing each `.put()` return, not
  // calling it as a statement) so they reach `getGlobalRoutes()` and therefore
  // the OpenAPI spec. Precise per-route types are intentionally dropped here —
  // these routes are consumed by third parties via OpenAPI, not Eden.
  return writableMetrics(profile).reduce<Elysia>(
    (acc, metric) => {
      const constraint = entityConstraint(metric);
      const rangeNote =
        constraint.valueType === "enum"
          ? `Allowed values: ${constraint.enumValues?.join(", ")}.`
          : constraint.min !== undefined || constraint.max !== undefined
            ? `Range: ${constraint.min ?? "-∞"}..${constraint.max ?? "∞"}${metric.unit ? ` ${metric.unit}` : ""}.`
            : "Unbounded numeric value.";
      return acc.put(
        `/entities/${metric.key}`,
        async ({ body }: { body: { value: number } }) => {
          await deps.write(metric.key, body.value);
          return { ok: true, key: metric.key, value: body.value };
        },
        {
          body: t.Object({ value: valueSchema(constraint) }),
          detail: {
            tags: ["Commands"],
            summary: `Set ${metric.label}`,
            description: `Write the "${metric.key}" setting. ${rangeNote}`,
          },
        },
      ) as unknown as Elysia;
    },
    app as unknown as Elysia,
  );
}
