/**
 * Auto-generated third-party integration API (`/api/v1`).
 *
 * Every route here is derived from the active inverter profile's entity
 * catalog — the catalog, the per-entity read routes, and one validated write
 * route per writable entity are all generated by looping {@link profile.metrics}.
 * Adding a metric to a profile (or installing a new inverter package) extends
 * this API and its OpenAPI docs with zero route code.
 *
 * Auth: guarded by `API_KEYS` (see the guard below). This is the external
 * surface; the web app's own session-authed endpoints live in `index.ts`.
 */

import { auth } from "@SunReye/auth";
import { env } from "@SunReye/env/server";
import type { EntityConstraint } from "@SunReye/inverter-core";
import { entityConstraint, writableMetrics } from "@SunReye/inverter-core";
import { Elysia, t } from "elysia";
import { queryRawHistory, queryRollup } from "./history";
import type { ProfileContext } from "./inverter";
import { log } from "./logging";
import { liveState } from "./state";

const logger = log("api");

/** TypeBox validator for a writable entity's value, from its constraint. */
function valueSchema(c: EntityConstraint) {
  if (c.valueType === "enum" && c.enumValues && c.enumValues.length > 0) {
    return t.Union(c.enumValues.map((v) => t.Literal(v)));
  }
  const bounds: { minimum?: number; maximum?: number } = {};
  if (c.min !== undefined) bounds.minimum = c.min;
  if (c.max !== undefined) bounds.maximum = c.max;
  return t.Number(bounds);
}

/** Extract the presented key from either `Authorization: Bearer` or `x-api-key`. */
function extractApiKey(request: Request): string | undefined {
  const header = request.headers.get("authorization");
  const bearer = header?.toLowerCase().startsWith("bearer ") ? header.slice(7).trim() : undefined;
  return bearer ?? request.headers.get("x-api-key") ?? undefined;
}

/**
 * Reject requests without a valid API key. Two credential sources are accepted:
 * the static `API_KEYS` env allow-list, and admin-issued keys managed by the
 * Better Auth API Key plugin (validated via `auth.api.verifyApiKey`, which also
 * enforces expiry/enabled and bumps the key's usage counters). Empty `API_KEYS`
 * stays open in development (local convenience) but fails closed in production
 * so the public surface is never accidentally unauthenticated.
 */
async function checkApiKey(request: Request): Promise<{ status: number; error: string } | null> {
  const keys = env.API_KEYS;

  // Dev convenience: with no static keys configured, the surface is open.
  if (keys.length === 0 && env.NODE_ENV !== "production") {
    return null;
  }

  const provided = extractApiKey(request);
  if (provided) {
    if (keys.includes(provided)) return null;
    // Fall back to a managed (DB-backed) key. verifyApiKey never throws for an
    // unknown key, but guard against adapter/DB errors so a transient failure
    // can't accidentally authorize a request.
    const res = await auth.api.verifyApiKey({ body: { key: provided } }).catch(() => null);
    if (res?.valid) return null;
  }

  // Production with no static keys and no presented credential: the operator
  // hasn't configured static access (managed keys are still accepted above).
  if (keys.length === 0 && !provided) {
    return { status: 401, error: "API access is not configured" };
  }
  return { status: 401, error: "Invalid or missing API key" };
}

/** Injected transport dependencies (keeps this module free of the singleton). */
export interface EntitiesApiDeps {
  /**
   * The active profile context (manifest, catalog), resolved at boot — or `null`
   * in onboarding-only boot, when there's no profile and thus no entity surface.
   */
  ctx: ProfileContext | null;
  write(key: string, value: number): Promise<void>;
}

/** Mount the generated `/api/v1` integration API onto an Elysia app. */
export function entitiesApi(deps: EntitiesApiDeps) {
  // Onboarding-only boot: no active profile, so no entities to generate. Mount an
  // empty group so the composition root can `.use()` it unconditionally.
  if (!deps.ctx) return new Elysia({ prefix: "/api/v1", name: "entities" });
  const { profile, manifest, metaByKey } = deps.ctx;
  const app = new Elysia({ prefix: "/api/v1", name: "entities" })
    .onError(({ error, code, set }) => {
      // Preserve the status of known request errors; sanitize everything else to
      // a generic 500 so internal stack traces never leak to third parties.
      if (code === "VALIDATION") {
        set.status = 422;
        return { error: "Validation failed", detail: error.message };
      }
      if (code === "PARSE") {
        set.status = 400;
        return { error: "Malformed request body" };
      }
      logger.error("{code}: {error}", {
        code,
        error: error instanceof Error ? error.stack : error,
      });
      set.status = 500;
      return { error: "Internal server error" };
    })
    .onBeforeHandle(async ({ request, set }) => {
      const denied = await checkApiKey(request);
      if (denied) {
        set.status = denied.status;
        return { error: denied.error };
      }
    })
    // Entity catalog: identity, label, unit, kind, role, topic, writability,
    // bounds/enum. The discovery endpoint a consumer reads first.
    .get(
      "/entities",
      () => ({
        id: manifest.id,
        name: manifest.name,
        manufacturer: manifest.manufacturer,
        capabilities: manifest.capabilities,
        entities: manifest.metrics,
      }),
      {
        detail: {
          tags: ["Entities"],
          summary: "List entities",
          description: "Full catalog of entities the active inverter exposes.",
        },
      },
    )
    // Current value of every entity in one snapshot (from the live poll cache).
    .get(
      "/state",
      ({ set }) => {
        const sample = liveState.latest;
        if (!sample) {
          set.status = 503;
          return { error: "No sample available yet" };
        }
        return { time: sample.time, inverterId: sample.inverterId, values: sample.metrics };
      },
      {
        detail: {
          tags: ["Entities"],
          summary: "Current state",
          description: "Latest value of every entity from the most recent poll.",
        },
      },
    )
    // One entity's metadata plus its latest value.
    .get(
      "/entities/:key",
      ({ params, set }) => {
        const meta = metaByKey.get(params.key);
        if (!meta) {
          set.status = 404;
          return { error: `Unknown entity: ${params.key}` };
        }
        return { ...meta, value: liveState.latest?.metrics[params.key] ?? null };
      },
      {
        params: t.Object({ key: t.String() }),
        detail: {
          tags: ["Entities"],
          summary: "Get entity",
          description: "Metadata and latest value for a single entity.",
        },
      },
    )
    // Time series for one entity. Raw samples by default; pass `bucket` to read
    // the pre-aggregated TimescaleDB rollups (cheap over long windows).
    .get(
      "/entities/:key/history",
      async ({ params, query, set }) => {
        if (!metaByKey.has(params.key)) {
          set.status = 404;
          return { error: `Unknown entity: ${params.key}` };
        }
        const inverterId = query.inverterId ?? profile.id;
        const since = new Date(Date.now() - query.hours * 60 * 60 * 1000);
        const base = { metric: params.key, inverterId, since, limit: query.limit };
        return query.bucket
          ? queryRollup({ ...base, bucket: query.bucket })
          : queryRawHistory(base);
      },
      {
        params: t.Object({ key: t.String() }),
        query: t.Object({
          hours: t.Number({ default: 24, minimum: 1 }),
          limit: t.Number({ default: 5000, minimum: 1, maximum: 50000 }),
          bucket: t.Optional(t.Union([t.Literal("minute"), t.Literal("hour"), t.Literal("day")])),
          inverterId: t.Optional(t.String()),
        }),
        detail: {
          tags: ["Entities"],
          summary: "Entity history",
          description:
            "Time series for one entity: raw samples, or aggregated rollups when `bucket` is set.",
        },
      },
    );

  // One validated write route per writable entity. Bounds/enum come from the
  // entity's metadata, so each route documents (and enforces) exactly what it
  // accepts. We fold routes into the chain (capturing each `.put()` return, not
  // calling it as a statement) so they reach `getGlobalRoutes()` and therefore
  // the OpenAPI spec. Precise per-route types are intentionally dropped here —
  // these routes are consumed by third parties via OpenAPI, not Eden.
  return writableMetrics(profile).reduce<Elysia>(
    (acc, metric) => {
      const constraint = entityConstraint(metric);
      const rangeNote =
        constraint.valueType === "enum"
          ? `Allowed values: ${constraint.enumValues?.join(", ")}.`
          : constraint.min !== undefined || constraint.max !== undefined
            ? `Range: ${constraint.min ?? "-∞"}..${constraint.max ?? "∞"}${metric.unit ? ` ${metric.unit}` : ""}.`
            : "Unbounded numeric value.";
      return acc.put(
        `/entities/${metric.key}`,
        async ({ body }: { body: { value: number } }) => {
          await deps.write(metric.key, body.value);
          return { ok: true, key: metric.key, value: body.value };
        },
        {
          body: t.Object({ value: valueSchema(constraint) }),
          detail: {
            tags: ["Commands"],
            summary: `Set ${metric.label}`,
            description: `Write the "${metric.key}" setting. ${rangeNote}`,
          },
        },
      ) as unknown as Elysia;
    },
    app as unknown as Elysia,
  );
}
